### ISSUE TITLE
安装electron V23.3.13版本报错

### ISSUE THREAD

**Issue by dengxueru** [alex8088/clipboard-files#19]
node 版本 V14.21.3，请问这个是什么原因
在控制台中打印node-gyp -v  版本是v10.1.0

<img width="1080" alt="企业微信截图_17138750434080" src="https://github.com/alex8088/clipboard-files/assets/38432260/cecf71a3-c8b0-4135-bfee-d5d96a55ad89">
<img width="899" alt="企业微信截图_17138750576048" src="https://github.com/alex8088/clipboard-files/assets/38432260/c23a7e17-9989-40d9-9ca0-2b26d349aabb">

**Comment by alex8088** [comment]
请确认安装了py，并升级node版本
