### ISSUE TITLE
MAC下用不了

### ISSUE THREAD

**Issue by shenlanchenwei** [alex8088/clipboard-files#2]
你好，我在MAC下编译的时候提示404
地址：https://github.com/alex8088/clipboard-files/releases/download/v0.0.9/node-v57-darwin-x64.tar.gz
能帮忙编译一个版本吗。

谢谢了

**Comment by alex8088** [comment]
> 你好，我在MAC下编译的时候提示404
> 地址：https://github.com/alex8088/clipboard-files/releases/download/v0.0.9/node-v57-darwin-x64.tar.gz
> 能帮忙编译一个版本吗。
> 
> 谢谢了

node 下，使用以下命令安装，也可以使用target参数指定node版本
npm i clipboard-files --build-from-source
electron下，使用以下命令安装：
 npm i clipboard-files --build-from-source --runtime=electron --target=7.1.2 --target-arch=ia32 --dist-url=https://atom.io/download/electron

**Comment by shenlanchenwei** [comment]
@alex8088 你好,我在windows平台下执行
npm i clipboard-files --build-from-source --runtime=electron --target=8.0.0 --target-arch=ia32 --dist-url=https://atom.io/download/electron
安装,最后他还是编译成64位,按道理应该要编译成32位的,请问您知道原因吗?

**Comment by alex8088** [comment]
try --target_arch=ia32

**Comment by alex8088** [comment]
> @alex8088 你好,我在windows平台下执行
> npm i clipboard-files --build-from-source --runtime=electron --target=8.0.0 --target-arch=ia32 --dist-url=https://atom.io/download/electron
> 安装,最后他还是编译成64位,按道理应该要编译成32位的,请问您知道原因吗?

try --target_arch=ia32

**Comment by shenlanchenwei** [comment]
> --target_arch=ia32
我的命令里就是这个,但是编译出来还是64位,这个好像不起作用一样

**Comment by liamcindy** [comment]
@alex8088 你好，麻烦问一下MAC下报错，是需要配置哪里么？

**Comment by alex8088** [comment]
> @alex8088 你好，麻烦问一下MAC下报错，是需要配置哪里么？
> 
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSViewController.h:247:39: error:
> unknown type name 'NSExtensionContext'; did you mean 'NSAnimationContext'?
> @Property (nullable, readonly,retain) NSExtensionContext *extensionContext API_AVAILABLE(macos(10.10));
> ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSAnimationContext.h:18:12: note:
> 'NSAnimationContext' declared here
> @interface NSAnimationContext : NSObject

不需要配置什么，是否在nodejs下使用，看报错信息和addon没有关系，请提供一下你使用方式的代码

**Comment by liamcindy** [comment]
@alex8088 你好，使用的这个命令
npm i clipboard-files --build-from-source --runtime=electron --target=4.2.12 --target-arch=ia32 --dist-url=https://atom.io/download/electron
我的系统是macOS 10.15.6

**Comment by alex8088** [comment]
> @alex8088 你好，使用的这个命令
> npm i clipboard-files --build-from-source --runtime=electron --target=4.2.12 --target-arch=ia32 --dist-url=https://atom.io/download/electron
> 我的系统是macOS 10.15.6

npm i clipboard-files --build-from-source --runtime=electron --target=4.2.12  --dist-url=https://atom.io/download/electron

macOS平台一般都是64位的

**Comment by liamcindy** [comment]
@alex8088 非常感谢

**Comment by alex8088** [comment]
close

**Comment by KotoriMinami** [comment]
@alex8088 你好，请问一下，我在mac下执行npm i clipboard-files --build-from-source --runtime=electron --target=10.0.0 --dist-url=https://atom.io/download/electron 以后，启动项目时提示

This dependency was not found:

* aws-sdk in ./node_modules/node-pre-gyp/lib/info.js, ./node_modules/node-pre-gyp/lib/publish.js and 1 other

To install it, you can run: npm install --save aws-sdk
是什么原因。 在win10下是正常的

**Comment by alex8088** [comment]
删除node_modules包，在你的项目package中去除clipboard-files，再install，完成后再单独安装clipboard-files

**Comment by KotoriMinami** [comment]
> > @alex8088 你好，请问一下，我在mac下执行npm i clipboard-files --build-from-source --runtime=electron --target=10.0.0 --dist-url=https://atom.io/download/electron 以后，启动项目时提示
> > This dependency was not found:
> > 
> > * aws-sdk in ./node_modules/node-pre-gyp/lib/info.js, ./node_modules/node-pre-gyp/lib/publish.js and 1 other
> > 
> > To install it, you can run: npm install --save aws-sdk
> > 是什么原因。 在win10下是正常的
> 
> npm包安装问题，尝试删除node_modules包，在你的项目package中去除clipboard-files，再install，完成后再单独安装clipboard-files

非常感谢，不过我按你说的步骤尝试了一下，问题好像依然存在
1. 删除node_modules
2. package.json中移除clipboard-files依赖
3. yarn安装依赖
4. 安装完成以后，再执行yarn add clipboard-files --build-from-source --runtime=electron --target=10.0.0 --dist-url=https://atom.io/download/electron 
5. 启动项目
经过以上步骤依旧会提示之前的错误

**Comment by cnchore** [comment]
@alex8088  你好，Darwin 20.6.0 ，node：14.17.5，帮忙编译一个clipboard-files@1.0.2

**Comment by alex8088** [comment]
> @alex8088 你好，Darwin 20.6.0 ，node：14.17.5，帮忙编译一个clipboard-files@1.0.2

是无法编译吗，使用1.0.4版本试一试

**Comment by cnchore** [comment]
@alex8088  1.0.4也不行
npm i clipboard-files@1.0.4 --build-from-source --runtime=electron --target=14.17.5 --target_arch=x64 --dist-url=https://atom.io/download/electron

> clipboard-files@1.0.4 install /Users/electron-demo/app/node_modules/clipboard-files
> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/binding/src/main.o
In file included from ../src/main.cc:5:
In file included from ../src/clip_osx.h:1:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:12:
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSBundle.h:91:143: error: function does not return NSString
- (NSAttributedString *)localizedAttributedStringForKey:(NSString *)key value:(nullable NSString *)value table:(nullable NSString *)tableName NS_FORMAT_ARGUMENT(1) NS_REFINED_FOR_SWIFT API_AVAILABLE(macos(12.0), ios(15.0), watchos(8.0), tvos(15.0));
                                                         ~~~~~~~~~~~~~~                                                                       ^                  ~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:103:48: note: expanded from macro 'NS_FORMAT_ARGUMENT'
        #define NS_FORMAT_ARGUMENT(A) __attribute__ ((format_arg(A)))
                                                      ^          ~
1 error generated.
make: *** [Release/obj.target/binding/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Users/.nvm/versions/node/v14.17.5/bin/node" "/Users/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/electron-demo/app/node_modules/clipboard-files/lib/binding/electron-v14.17-darwin-x64/binding.node" "--module_name=binding" "--module_path=/Users/electron-demo/app/node_modules/clipboard-files/lib/binding/electron-v14.17-darwin-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v14.17"
gyp ERR! cwd /Users/electron-demo/app/node_modules/clipboard-files
gyp ERR! node -v v14.17.5
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/.nvm/versions/node/v14.17.5/bin/node /Users/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/electron-demo/app/node_modules/clipboard-files/lib/binding/electron-v14.17-darwin-x64/binding.node --module_name=binding --module_path=/Users/electron-demo/app/node_modules/clipboard-files/lib/binding/electron-v14.17-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v14.17' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/electron-demo/app/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Darwin 20.6.0
node-pre-gyp ERR! command "/Users/.nvm/versions/node/v14.17.5/bin/node" "/Users/electron-demo/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/electron-demo/app/node_modules/clipboard-files
node-pre-gyp ERR! node -v v14.17.5
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
node-pre-gyp ERR! not ok 
Failed to execute '/Users/.nvm/versions/node/v14.17.5/bin/node /Users/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/electron-demo/app/node_modules/clipboard-files/lib/binding/electron-v14.17-darwin-x64/binding.node --module_name=binding --module_path=/Users/electron-demo/app/node_modules/clipboard-files/lib/binding/electron-v14.17-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v14.17' (1)
npm WARN flyele@1.7.100 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clipboard-files@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the clipboard-files@1.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.npm/_logs/2022-05-09T11_33_46_435Z-debug.log

**Comment by alex8088** [comment]
@cnchore 你的target目标14.17.4并不存在，你看看你electron版本是多少

**Comment by alex8088** [comment]
@cnchore target 应该指定electron的版本而不是node的版本

**Comment by jsqq520** [comment]
您好，我在我在windows平台下执行
npm i clipboard-files --build-from-source --runtime=electron --target=15.3.5 --target_arch=x64 --dist-url=https://atom.io/download/electron
报错了，node版本是v16.14.0，Python 2.7.18
![image](https://user-imag@alex8088 s.githubusercontent.com/39544880/168030898-a997fe84-3c37-4759-868f-7b9091bc9338.png)
@

**Comment by jsqq520** [comment]
您好，我在我在windows平台下执行
npm i clipboard-files --build-from-source --runtime=electron --target=15.3.5 --target_arch=x64 --dist-url=https://atom.io/download/electron
报错了，node版本是v16.14.0，Python 2.7.18
![image](https://user-images.githubusercontent.com/39544880/168031026-19c52109-de25-40a3-9940-a2cf1971e0cb.png)
@alex8088

**Comment by jsqq520** [comment]
您好，我在我在windows平台下执行
```
npm i clipboard-files --build-from-source --runtime=electron --target=15.3.5 --target_arch=x64 --dist-url=https://atom.io/download/electron
```
报错了，node版本是v16.14.0，Python 3.10.4
![](https://user-images.githubusercontent.com/39544880/168031026-19c52109-de25-40a3-9940-a2cf1971e0cb.png)
@alex8088

**Comment by alex8088** [comment]
@jsqq520 electron headers下载不了 --dist-url 改成 https://electronjs.org/headers 试一试

**Comment by jsqq520** [comment]
> @jsqq520 electron headers下载不了 --dist-url 改成 https://electronjs.org/headers 试一试

已经可以了，谢谢
