### ISSUE TITLE
使用 yarn 或 npm 安装报错，系统是 windows10，框架：vue。请问这个还需要安装其它依赖组件吗

### ISSUE THREAD

**Issue by GHZhi** [alex8088/clipboard-files#4]
[1/11] ⢀ clipboard-files
[-/11] ⢀ waiting...
[6/11] ⢀ node-sass
[10/11] ⢀ spectron
error D:\文档\项目\Fincy\fincy-desktop\node_modules\postinstall-postinstall: Command 
failed.ll
Exit code: 1
Command: node ./run.js
Arguments:

gyp ERR! cwd D:\文档\项目\Fincy\fincy-desktop\node_modules\clipboard-files
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\文档\项目\Fincy\fincy-desktop\node_modules\clipboard-files\lib\binding\electron-v10.1-win32-x64\binding.node --module_name=binding --module_path=D:\文档\项目\Fincy\fincy-desktop\node_modules\clipboard-files\lib\binding\electron-v10.1-win32-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v10.1 --dist-url=https://atom.io/download/electron' (1)    
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\文档\项目\Fincy\fincy-desktop\node_modules\clipboard-files\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)        
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\文档\\项目\\Fincy\\fincy-desktop\\node_modules\\clipboard-files\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\文档\项目\Fincy\fincy-desktop\node_modules\clipboard-files  
node-pre-gyp ERR! node -v v14.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clipboard-files@0.0.9 install: `node-pre-gyp install --fallback-to-build`   
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the clipboard-files@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging 
output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Zhi\AppData\Roaming\npm-cache\_logs\2020-09-23T11_27_38_190Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Fincy@1.0.0 cf-rebuild: `npm rebuild clipboard-files --build-from-source --runtime=electron --target=10.1.2 --dist-url=https://atom.io/download/electron`        
npm ERR! Exit status 1

**Comment by alex8088** [comment]
使用 npm i clipboard-files --build-from-source --runtime=electron --target=10.1.2 --dist-url=https://atom.io/download/electron 独立安装
