### ISSUE TITLE
安装完引入使用时报package.json not exist

### ISSUE THREAD

**Issue by yyg1219** [alex8088/clipboard-files#8]
![image](https://user-images.githubusercontent.com/38304911/150926027-fe0a7128-e3bd-402f-9172-635615af5211.png)

您好，我在electron项目中安装完成之后，在引入使用时报以上错误，请问是为什么呢

**Comment by alex8088** [comment]
> ![image](https://user-images.githubusercontent.com/38304911/150926027-fe0a7128-e3bd-402f-9172-635615af5211.png)
> 
> 您好，我在electron项目中安装完成之后，在引入使用时报以上错误，请问是为什么呢

use only in main process
