### ISSUE TITLE
windows打包有错误日志，安装包打不开？

### ISSUE THREAD

**Issue by jsqq520** [alex8088/clipboard-files#9]
![image](https://user-images.githubusercontent.com/39544880/168060430-098e99e1-9c22-48cf-8881-f41d347c4f96.png)
![image](https://user-images.githubusercontent.com/39544880/168061272-0924cead-f3f3-4a06-92fb-4ae820472e61.png)
你好，我这边本地运行都是正常的，打包后，打开就报这个错误。 @alex8088

**Comment by alex8088** [comment]
你用什么构建，要在external 中排除

**Comment by jsqq520** [comment]
externals配置可以了，mac这边打包有签名的问题，能不能把包签名一下呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月12日(星期四) 晚上8:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alex8088/clipboard-files] windows打包有错误日志，安装包打不开？ (Issue #9)





 
你用什么构建，要在external 中排除

**Comment by rhwoodpecker** [comment]
因为在external中排除了该包，导致重新安装生产依赖后编译出来的 node文件，绕开了electron-builder的代码签名

**Comment by rhwoodpecker** [comment]
> 因为在external中排除了该包，导致重新安装生产依赖后编译出来的 node文件，绕开了electron-builder的代码签名

<img width="260" alt="image" src="https://user-images.githubusercontent.com/22131908/168195396-36bdfb94-6d75-4e45-ab57-01e6797c6f54.png">

**Comment by alex8088** [comment]
这应该和模块本身无关，你可以在electron-builder中找到类似的问题

你的 electron-builder 是否保持较新版本

关于electron-builder rebuild，如果确认arch就是你要构建的，可以加以下配置，看是否解决你的问题

```
asarUnpack:
  - node_modules/clipboard-files
npmRebuild: false
```

对node原生模块建议排除在asar之外

**Comment by rhwoodpecker** [comment]
> 这应该和模块本身无关，你可以在electron-builder中找到类似的问题
> 
> 你的 electron-builder 是否保持较新版本
> 
> 关于electron-builder rebuild，如果确认arch就是你要构建的，可以加以下配置，看是否解决你的问题
> 
> ```
> asarUnpack:
>   - node_modules/clipboard-files
> npmRebuild: false
> ```
> 已修复 谢谢
> 对node原生模块建议排除在asar之外
